import type { TranslationReport, FileReport, ErrorEntry } from '../types/translation';
import { formatDuration, getStatusEmoji } from './reporter';

/**
 * Generate a markdown report
 */
export function generateMarkdownReport(report: TranslationReport): string {
  const sections: string[] = [];

  // Header
  sections.push(generateHeader(report));

  // Summary section
  sections.push(generateSummarySection(report));

  // File details section
  if (report.files.length > 0) {
    sections.push(generateFilesSection(report.files));
  }

  // Errors section
  if (report.errors.length > 0) {
    sections.push(generateErrorsSection(report.errors));
  }

  // Footer
  sections.push(generateFooter());

  return sections.join('\n\n');
}

/**
 * Generate report header
 */
function generateHeader(report: TranslationReport): string {
  const status = getStatusEmoji(report);
  return `# ${status} Translation Report

**Generated:** ${report.endTime.toISOString()}
**Duration:** ${formatDuration(report.durationMs)}`;
}

/**
 * Generate summary section
 */
function generateSummarySection(report: TranslationReport): string {
  const { summary, config } = report;

  return `## Summary

| Metric | Value |
|--------|-------|
| Provider | ${config.provider}${config.model ? ` (${config.model})` : ''} |
| Source Language | ${config.sourceLanguage} |
| Target Languages | ${config.targetLanguages.join(', ')} |
| Files Processed | ${summary.totalFiles} |
| Total Strings | ${summary.totalUnits} |
| Translated | ${summary.translatedUnits} |
| Skipped | ${summary.skippedUnits} |
| Failed | ${summary.failedUnits} |
| Success Rate | ${calculateSuccessRate(summary)}% |`;
}

/**
 * Generate files section
 */
function generateFilesSection(files: FileReport[]): string {
  if (files.length === 0) {
    return '';
  }

  const rows = files
    .map(file => {
      const status = file.unitsFailed > 0 ? '⚠️' : '✅';
      return `| ${status} | \`${file.filePath}\` | ${file.targetLanguage} | ${file.unitsTranslated}/${file.unitsProcessed} |`;
    })
    .join('\n');

  return `## Files

| Status | File | Language | Translated |
|--------|------|----------|------------|
${rows}`;
}

/**
 * Generate errors section
 */
function generateErrorsSection(errors: ErrorEntry[]): string {
  if (errors.length === 0) {
    return '';
  }

  const items = errors
    .map(error => {
      let location = '';
      if (error.filePath) {
        location += `\`${error.filePath}\``;
      }
      if (error.unitId) {
        location += location ? ` (${error.unitId})` : error.unitId;
      }

      return `- **${error.code}**: ${error.message}${location ? `\n  - Location: ${location}` : ''}`;
    })
    .join('\n');

  return `## Errors

${items}`;
}

/**
 * Generate footer
 */
function generateFooter(): string {
  return `---

*Generated by i18n-translate-action*`;
}

/**
 * Calculate success rate percentage
 */
function calculateSuccessRate(summary: TranslationReport['summary']): string {
  if (summary.totalUnits === 0) {
    return '100';
  }

  const rate = (summary.translatedUnits / (summary.totalUnits - summary.skippedUnits)) * 100;
  return rate.toFixed(1);
}

/**
 * Generate a compact summary for PR comments
 */
export function generateCompactSummary(report: TranslationReport): string {
  const status = getStatusEmoji(report);
  const { summary, config } = report;

  let result = `${status} **Translation Update**\n\n`;
  result += `Translated **${summary.translatedUnits}** strings across **${summary.totalFiles}** files\n`;
  result += `Languages: ${config.sourceLanguage} → ${config.targetLanguages.join(', ')}\n`;

  if (summary.failedUnits > 0) {
    result += `\n⚠️ ${summary.failedUnits} strings failed to translate`;
  }

  return result;
}

/**
 * Generate a table of changes for PR description
 */
export function generateChangesTable(files: FileReport[]): string {
  if (files.length === 0) {
    return 'No files were updated.';
  }

  const header = '| File | Language | Changes |';
  const separator = '|------|----------|---------|';

  const rows = files
    .filter(f => f.unitsTranslated > 0)
    .map(f => `| ${f.filePath} | ${f.targetLanguage} | +${f.unitsTranslated} |`)
    .join('\n');

  if (!rows) {
    return 'No files were updated.';
  }

  return `${header}\n${separator}\n${rows}`;
}

/**
 * Generate badges for README
 */
export function generateBadges(report: TranslationReport): string {
  const { summary } = report;

  const coverage =
    summary.totalUnits > 0 ? Math.round((summary.translatedUnits / summary.totalUnits) * 100) : 100;

  const color = coverage >= 90 ? 'brightgreen' : coverage >= 70 ? 'yellow' : 'red';

  return `![Translation Coverage](https://img.shields.io/badge/translations-${coverage}%25-${color})`;
}

/**
 * Generate JSON summary for machine parsing
 */
export function generateJsonSummary(report: TranslationReport): string {
  return JSON.stringify(
    {
      success: report.errors.length === 0 && report.summary.failedUnits === 0,
      duration_ms: report.durationMs,
      provider: report.config.provider,
      model: report.config.model,
      source_language: report.config.sourceLanguage,
      target_languages: report.config.targetLanguages,
      files_processed: report.summary.totalFiles,
      strings_total: report.summary.totalUnits,
      strings_translated: report.summary.translatedUnits,
      strings_skipped: report.summary.skippedUnits,
      strings_failed: report.summary.failedUnits,
      errors: report.errors.length,
    },
    null,
    2
  );
}
